import type { LaborRates } from '../types'

export const NON_UNION_RATE: LaborRates = {
  local: 'Non-Union',
  stStraight: 55,
  stOT: 82.5,
  stDT: 110,
  laborNote: 'Non-union labor.',
}

export const UNION_RATES: Record<string, LaborRates> = {
  'las vegas': {
    local: 'Las Vegas, NV',
    stStraight: 85,
    stOT: 127.5,
    stDT: 170,
    laborNote: 'IATSE Local 720. OT after 8h, DT after 12h and weekends.',
  },
  'las vegas nv': {
    local: 'Las Vegas, NV',
    stStraight: 85,
    stOT: 127.5,
    stDT: 170,
    laborNote: 'IATSE Local 720. OT after 8h, DT after 12h and weekends.',
  },
  chicago: {
    local: 'Chicago, IL',
    stStraight: 90,
    stOT: 135,
    stDT: 180,
    laborNote: 'IATSE Local 2. OT after 8h, DT after 12h and weekends.',
  },
  'chicago il': {
    local: 'Chicago, IL',
    stStraight: 90,
    stOT: 135,
    stDT: 180,
    laborNote: 'IATSE Local 2. OT after 8h, DT after 12h and weekends.',
  },
  'new york': {
    local: 'New York, NY',
    stStraight: 110,
    stOT: 165,
    stDT: 220,
    laborNote: 'IATSE Local 1. OT after 8h, DT after 12h and weekends.',
  },
  'new york ny': {
    local: 'New York, NY',
    stStraight: 110,
    stOT: 165,
    stDT: 220,
    laborNote: 'IATSE Local 1. OT after 8h, DT after 12h and weekends.',
  },
  orlando: {
    local: 'Orlando, FL',
    stStraight: 75,
    stOT: 112.5,
    stDT: 150,
    laborNote: 'IATSE Local 835. OT after 8h, DT after 12h and weekends.',
  },
  'los angeles': {
    local: 'Los Angeles, CA',
    stStraight: 95,
    stOT: 142.5,
    stDT: 190,
    laborNote: 'IATSE Local 33. OT after 8h, DT after 12h and weekends.',
  },
  'san francisco': {
    local: 'San Francisco, CA',
    stStraight: 100,
    stOT: 150,
    stDT: 200,
    laborNote: 'IATSE Local 16. OT after 8h, DT after 12h and weekends.',
  },
  boston: {
    local: 'Boston, MA',
    stStraight: 92,
    stOT: 138,
    stDT: 184,
    laborNote: 'IATSE Local 11. OT after 8h, DT after 12h and weekends.',
  },
  dallas: {
    local: 'Dallas, TX',
    stStraight: 72,
    stOT: 108,
    stDT: 144,
    laborNote: 'IATSE Local 127. OT after 8h, DT after 12h and weekends.',
  },
  atlanta: {
    local: 'Atlanta, GA',
    stStraight: 70,
    stOT: 105,
    stDT: 140,
    laborNote: 'IATSE Local 927. OT after 8h, DT after 12h and weekends.',
  },
  denver: {
    local: 'Denver, CO',
    stStraight: 78,
    stOT: 117,
    stDT: 156,
    laborNote: 'IATSE Local 7. OT after 8h, DT after 12h and weekends.',
  },
  seattle: {
    local: 'Seattle, WA',
    stStraight: 88,
    stOT: 132,
    stDT: 176,
    laborNote: 'IATSE Local 15. OT after 8h, DT after 12h and weekends.',
  },
  phoenix: {
    local: 'Phoenix, AZ',
    stStraight: 68,
    stOT: 102,
    stDT: 136,
    laborNote: 'IATSE Local 631. OT after 8h, DT after 12h and weekends.',
  },
  houston: {
    local: 'Houston, TX',
    stStraight: 70,
    stOT: 105,
    stDT: 140,
    laborNote: 'IATSE Local 51. OT after 8h, DT after 12h and weekends.',
  },
  miami: {
    local: 'Miami, FL',
    stStraight: 73,
    stOT: 109.5,
    stDT: 146,
    laborNote: 'IATSE Local 500. OT after 8h, DT after 12h and weekends.',
  },
  'new orleans': {
    local: 'New Orleans, LA',
    stStraight: 68,
    stOT: 102,
    stDT: 136,
    laborNote: 'IATSE Local 39. OT after 8h, DT after 12h and weekends.',
  },
  anaheim: {
    local: 'Anaheim, CA',
    stStraight: 95,
    stOT: 142.5,
    stDT: 190,
    laborNote: 'IATSE Local 504. OT after 8h, DT after 12h and weekends.',
  },
  nashville: {
    local: 'Nashville, TN',
    stStraight: 65,
    stOT: 97.5,
    stDT: 130,
    laborNote: 'IATSE Local 46. OT after 8h, DT after 12h and weekends.',
  },
}
